### ISSUE TITLE
v1.0.0开发统计

### ISSUE THREAD

**Issue by toimc** [toimc-team/vue3-toimc-admin#14]
对于没有任务的同学，可以自行先定开发计划，如：https://github.com/toimc-team/vue3-toimc-admin/issues/10

找一个竞品中自己最熟悉，或者最感兴趣的部分着手。

目前：

- [x] @[前端]Forest-Forest-211 在做登录相关mock https://github.com/toimc-team/vue3-toimc-admin/issues/17 
- [x] @[前端]白叶 在做编辑器，主题配置，layout与menu的优化，竞品对标vue-admin，vben https://github.com/toimc-team/vue3-toimc-admin/issues/19 https://github.com/toimc-team/vue3-toimc-admin/issues/20
- [x] @[前端]🐳 alive-whalesink 在做echarts图表相关
- [x] @[前端]小王-EchoWhw 密码强度组件 https://github.com/toimc-team/vue3-toimc-admin/issues/24
- [x] @[前端]-书生-idxiu  系统管理、角色管理、菜单管理、部门管理、数据字典 https://github.com/toimc-team/vue3-toimc-admin/issues/15
- [x] @[前端]依韵-cdswyda Slide组件定制，水印，全屏 https://github.com/toimc-team/vue3-toimc-admin/issues/16
- [x] @[前端]尚可-2019997204、@[前端]小麦-weihanling Excel的编辑、导入、导出
- [x] @[前端]泽龙-zelong  页面-详情页
- [x] @[前端]小景-coderJerry @[前端]小源-Small-source 了解竞品相关的需求
- [x] @[前端]方头-woodenF form高级玩法

可能延期的功能开发
- [ ] @[全栈]黑兔-blackitrabbit websocket
- [ ] @[前端]小刘刘-peri-520 PDF下载 与 在线形成，包括图片
- [x] @前端-波仔 @[Jakeyhb](https://github.com/Jakeyhb) 首页、看板、统计数据
- [x]  @[前端]依韵-cdswyda音频组件、视频组件
- [x] @[前端]泽龙-Alanz0221 首页大屏 https://github.com/toimc-team/vue3-toimc-admin/issues/66
- [x] @[全栈]东东-xudongdong40 在做 日历相关，倒计时，热门列表，瀑布流 https://github.com/toimc-team/vue3-toimc-admin/issues/11

对于没有任务的同学，可以自行先定开发计划，如：https://github.com/toimc-team/vue3-toimc-admin/issues/10

找一个竞品中自己最熟悉，或者最感兴趣的部分着手。

![image](https://user-images.githubusercontent.com/51934415/161428208-9bb81bdf-c3d5-4732-9273-211ce5958236.png)

**Comment by toimc** [comment]
目前空缺的开发功能

- [ ] Websocket utils 
- [ ] Websocket 消息通信
- [ ] 视频组件 播放 与 控制
- [ ] 音频组件 播放 与 控制
- [ ] PDF下载 与 在线形成，包括图片
- [ ] Excel编辑 下载 上传
- [ ] 菜单相关：Layout，定制主题，标签面等
- [ ] Slide组件 -> 定制
- [ ] 水印
- [ ] 全屏
- [ ] Form的布局，Form拖拽，可编辑的Form
- [ ] 引导页
- [ ] Tab, Menu带参
- [ ] 权限设计：路由权限、接口角色权限、按钮的directive
- [ ] 首页、看板、统计数据
- [ ] （非重要）业务类型的组件

**Comment by 2019997204** [comment]
- [ ] 表格的编辑、导入、导出

**Comment by cdswyda** [comment]
claim

- [ ] Slide组件 -> 定制
- [ ] 水印
- [ ] 全屏

**Comment by peri-520** [comment]
PDF下载 与 在线形成，包括图片

**Comment by peri-520** [comment]
> * [ ]  PDF下载 与 在线形成，包括图片

**Comment by Jakeyhb** [comment]
- [首页、看板、统计数据]

**Comment by Jakeyhb** [comment]
- [ ] 首页、看板、统计数据

**Comment by a1597284782** [comment]
- [ ] 引导页
